### PR TITLE
Check for latest version by using tags (oh, and stop crashing. That's also good.)

### PR DESCRIPTION
**Pull request by bbriggs**

### CODE REVIEW

**Comment by bbriggs** [comment]
15:57:21     @fraq | !msync
15:57:22 TheVoxFox | modulesync_config_version: '0.15.1

**Comment by bbriggs** [comment]
20:46:38     @fraq | !msync getver puppet-network
20:46:40 TheVoxFox | modulesync_config_version: '0.15.0'

**Comment by bbriggs** [comment]
@bastelfreak

**Comment by bbriggs** [comment]
This closes #1

**Comment by bbriggs** [comment]
This is the patch that never ends! It goes on and on my friends...

What started as a patch to fix a stack trace turned into me extending it into properly using the API to find tags instead of naïvely looking at a file in the repo.

**Comment by bastelfreak** [comment]
I tested this, and it is working fine right now. :+1: for merging.

```
2016-11-19 10:34:50 bastelfreak !msync getver puppet-mumble 
2016-11-19 10:34:51 TheVoxFox1337       modulesync_config_version: '0.15.0' 
2016-11-19 10:35:55 bastelfreak !msync 
2016-11-19 10:35:55 TheVoxFox1337       0.15.0
```

**Pull request merged**
