### PR TITLE
unpin legobot requirement

### PR DESCRIPTION
**Pull request by bastelfreak**
since this is stable, do we really need to pin it?

### CODE REVIEW

**Comment by sacres** [comment]
I'd suggest we actually pin everything in requirements.txt 
Please see: [Pip repeatability](https://pip.pypa.io/en/latest/user_guide/#repeatability)

**Comment by bbriggs** [comment]
Agree, pin all your dependencies.

**Comment by sacres** [comment]
I've provided an inverse PR to this provided we (and whomever else would like to weigh in) agree.

**Comment by dhoppe** [comment]
Usually I would agree, but who cares about the new versions to test / maintain? In the files `.fixtures.yml` and` metadata.json` we do not use static versions.

**Comment by sacres** [comment]
@dhoppe The rationale for pinning dependencies within requirements.txt is to maintain a reproducible product. 
PythonCQA is making great strides these days wrt/ packaging (compared to the dismal past), but it's not the case _yet_ . 
We're also working on dependency and code checking automation tools with this repo.

**Comment by bbriggs** [comment]
I'm the maintainer up the upstream for the main package we use (Legobot). I'd say that I promise to do my best not to introduce breaking changes but I'd still recommend pinning. Always pin in operations as a matter of stability.

Consumers of our products are pinning our packages int their envs as a matter of stability. We can update as often as we like and by pinning versions, they can be confident we won't push a change to them they're not ready for. Likewise, we should pin here lest I or another upstream package make a breaking change. Simple fix to prevent heartache.

**Pull request closed without merging**
