### PR TITLE
Break channel config out to config.ini and amend example,

### PR DESCRIPTION
**Pull request by sacres**
Also:
Fix quoting & stray '=' in Factoids
This PR replaces #21 @bastelfreak @bbriggs

### CODE REVIEW

**Comment by bastelfreak** [comment]
LGTM, @bbriggs what do you think?

**Review by bbriggs — APPROVED** [review]

**Comment by bbriggs** [comment]
Yep, LGTM

**Comment by sacres** [comment]
Thanks!

**Comment by bbriggs** [comment]
No, thank *you*

**Pull request merged**
